name: "Nx CI"
on: [push, pull_request]
jobs:
  test:
    name: 'Unit test'
    runs-on: ubuntu-latest
    steps:
      # Checkout and install
      - name: checkout
        uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install deps
        run: yarn install
      - name: Build prequisite tools
        run: yarn run build-tools
      - name: Build prequisite dependencies
        uses: mansagroup/nrwl-nx-action@v2.0.4
        with:
          projects: svelte-preprocess
          targets: build
      - name: Unit test
        uses: mansagroup/nrwl-nx-action@v2.0.4
        with:
          projects: kairo,ng-lib,vue-lib,react-lib,svelte-lib,solid-lib,preact-lib
          targets: test
          affected: true
          args: --codeCoverage
      - name: Unit test for React Concurrent Mode
        uses: mansagroup/nrwl-nx-action@v2.0.4
        with:
          projects: react-lib
          targets: test-cm
          affected: true
          args: --codeCoverage
      - name: Unit test for Svelte SSR
        uses: mansagroup/nrwl-nx-action@v2.0.4
        with:
          projects: svelte-lib
          targets: test-ssr
          affected: true
          args: --codeCoverage
      - name: Merge coverage reports
        run: node ./merge-coverage.js
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}